### PR TITLE
added travis build badge to README; switched to filetype .md

### PR DESCRIPTION
**Pull request by r0fls**

### CODE REVIEW

**Comment by onyxfish** [comment]
There are additional wrinkles that makes this a bit more complicated. `setup.py` and `docs/index.rst` both reference the README and assume it is text.

**Comment by r0fls** [comment]
OK, I updated those to reference the README.md as a markdown file instead of text.

**Comment by onyxfish** [comment]
Right, but those files don't know how to parse markdown, so they are going to end up with unformatted badge code and stuff in there. We're either going to need to render the markdown or not use the README for those purposes.

**Comment by r0fls** [comment]
Maybe use pandoc to parse the .md first? http://pandoc.org

**Comment by onyxfish** [comment]
Messed with this for a while, but couldn't come up with a solution that was superior to just having two files. I don't like it, but whatever. Thanks for contributing!

**Pull request merged**
