### PR TITLE
Implement Table.homogenize. Closes #407

### LINKED ISSUE #407: Need a way to fill "gaps" in a dataset
What is the method that goes through a dataset and adds rows for those that don't exist. Needs to take a lambda that returns default data. (Or simply a default data array.) But what are the inputs. Can this be made generic?

```
table.fillgaps(compare_values, compare_func, default_row_array_or_func)
```

### PR DESCRIPTION
**Pull request by nbedi**
Here's my attempt at Table.homogenize. 

@onyxfish Not sure if it is exactly what you were looking for or as generic as you hoped. Leaving pull request open so you can check when you have a chance.

### CODE REVIEW

**Comment by onyxfish** [comment]
I like everything about this except the hard limit to one identifying column. What if you modified the first argument so it followed the `key` format of, for example, `order_by`. So the first argument could be lambda which would be applied to each row to return a unique value. That way you could essentially compare unlimited columns.

The 2nd arg is then any sequence (or generator) of values (which could be comparable sequences). I see you're already testing with `range` so that's great. It would probably be good to add a test with a custom generator function too, maybe one that returns a series of years as strings.

I like the `default_row` approach. You should specify in the docs somewhere that the lambda takes a value from the series and thus can compute its missing values using that data. I think the lambda should return the entire row though and you can leave it to the user to insert the keys. Or, in the simple case, you could supply a default lambda that returns `[key, None, None, ...]`.

Does that make sense?

**Comment by onyxfish** [comment]
Thinking some more, we should def have a default lambda behavior. That's almost always the functionality I want and its a tricky thing for the user to specify since they don't necessarily know how many columns there are in the table.

**Comment by nbedi** [comment]
Ah, now I get what compare_values and compare_func would be in your original comment on the issue. Thanks! Great points to make this a more powerful function. Looking into it adding all of this.

**Comment by nbedi** [comment]
Hmm, suggestions on how default row should behave when given a key function? If I use a key function that sums two columns, the generated rows could have any values for those columns.

**Comment by onyxfish** [comment]
That's a good point. Maybe in this case it would make more sense for it to be one or an array of column names rather than a key function.

**Comment by onyxfish** [comment]
And then the 2nd argument is either an array of single values or an array of sequences with length equal to the first argument. (And anything else would be an error condition.)

**Comment by nbedi** [comment]
@onyxfish How does it look with the updates?

**Comment by onyxfish** [comment]
Sorry, I missed that you had updated this. It looks great! Let's merge it in!

**Comment by nbedi** [comment]
No worries, I only recently updated. Merging now.

**Comment by onyxfish** [comment]
Just FYI, I did make a small follow-up commit to allow a single column name to be passed without being a list—for consistency with `order_by`, `distinct` and `join`.

**Comment by nbedi** [comment]
:+1:

**Pull request merged**
