### PR TITLE
Implements from_json to Table method, requested feature.

### PR DESCRIPTION
**Pull request by r0fls**
Proposed feature from Issue #344 and initial tests. Currently it only supports flat json items seperated by a new line, but it should probably be made to support a list too. May want to support nested dictionaries as well.

### CODE REVIEW

**Comment by onyxfish** [comment]
Hey Raphael, this looks like a great start. I appreciate you being so thorough with your docstrings. A few thoughts:

* I think you forgot to commit your `examples/test.json`.
* We probably want to default to parsing the entire file and assuming its an array of rows. I'm cool with also supporting the line-delimited case, but that's a relative rarity by comparison.
* Nested dictionaries I care less about (I just don't see them very often), but I'd like to support something equivalent to the `key` argument in [csvkit's parser](https://github.com/onyxfish/csvkit/blob/master/csvkit/convert/js.py#L40). This is both for compatibility and also because it's a case I've seen with a lot of real-world data.

**Comment by r0fls** [comment]
Awesome, thanks for the pointers. I'll make those changes. If you can assign it to me that would be nice.

**Comment by r0fls** [comment]
Hey, so just to be sure -- do you want it to default to parsing an array of rows without any newlines? So, something like this:

    [{"one":"1","two":"4","three":"a"},{"one":"2","two":"3","three":"b"},{"one":"","two":"2","three":"👍  "}]


Or:

    [{"one":"1","two":"4","three":"a"},
    {"one":"2","two":"3","three":"b"},
    {"one":"","two":"2","three":"👍  "}]


I think the first one makes more sense, and is surely easier to implement. But if someone wants a human readable data file (which they may) the former format would detract from that.

**Comment by onyxfish** [comment]
I think the default should just be parse the entire contents of the file as
a single JSON object, so the presence or absence of newlines shouldn't
matter. Run `json.load` over the entire file and then iterate over the
result assuming its a list.

**Comment by r0fls** [comment]
OK thanks, I think it's good to go. I can try to rebase the commits if you need it.

**Comment by onyxfish** [comment]
Looks good! Just reopening until I get a chance to merge and verify.

**Comment by r0fls** [comment]
OK, sounds good. I also tried fixing the reason that I had to comment out the JSON test that compares data types. I did so by adding a `__ne__` and `__eq__` methods in `data_types/base.py`. It was failing because they were different instances of the data type. Not sute why it worked for csv. It fails for python3 though.

**Comment by onyxfish** [comment]
@r0fls I merged this in and did some polishing. I took a big chunk of existing code from csvkit that allows it to support nested objects in the JSON and also elaborated the tests quite a bit. I was able to rewrite them so they wouldn't rely on those magic equality methods. (Which I don't think make sense in this case since two datatypes of the same class aren't truly equivalent.)

If you've got any questions about the changes I've made I'm happy to explain.

Thanks again for jumping in on this!

**Pull request merged**
