### PR TITLE
Added new Percent computation class and unittests

### PR DESCRIPTION
**Pull request by palewire**
For #490

### CODE REVIEW

**Comment by nbedi** [comment]
Thanks for the pull request! 

I'm not on my computer so I can't test this for myself but shouldn't `ZeroDivisionError` only occur if total is 0? Asking since we may actually want to throw an error if total is zero.

**Comment by palewire** [comment]
I just tested to be sure. You are right. I'm fine with handling it some other way, say throwing an error earlier up the chain.

```bash
>>> 0/100
0
>>> 0/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
```

**Comment by nbedi** [comment]
An error higher up sounds good, probably error for any totals less than or equal to 0 since a percent of a negative number doesn't make sense. 

Also, we should change `if self._total` to `if self._total is not None` to act as expected since it'll skip any values that are falsey.

**Comment by palewire** [comment]
I believe I have made those changes and pushed them moments ago.

**Comment by nbedi** [comment]
Merged! Thanks again. I just made some minor edits and an additional check if the sum of column values ends up being <= 0.

**Comment by palewire** [comment]
Hey! Proud to join as a contributor. I'll try to kick in some docs on this soon.

**Comment by onyxfish** [comment]
Thanks, Ben!

**Pull request merged**
